apriltag:
  ros__parameters:
    family: 36h11
    size: 0.166
    max_hamming: 0
    detector:
      threads: 2
      decimate: 1.0
      blur: 0.0
      refine_edges: 1
      sharpening: 0.25
      # 'debug' is a boolean parameter; using an integer caused a crash
      debug: false
    publish_tf: true