# zed_sim_params.yaml
zed_node:
  ros__parameters:
    sim_mode: true
    use_sim_time: true

    # Point these at your bridged topics
    left_topic: '/camera/left/image_raw'
    right_topic: '/camera/right/image_raw'
    left_cam_info_topic: '/camera/left/camera_info'
    right_cam_info_topic: '/camera/right/camera_info'
    depth_topic: '/camera/depth/image_raw'